Repository mbobrovskyi/chat-go, pull requests merged in 2025-03, with the labels that each got.

#24 chore: mock user server
  deployment/local/config/spec.json
  deployment/local/docker-compose.yaml
Labels: cleanup

#26 chore: use default project path
  Makefile
  test/e2e/e2e_test.go
  test/util/constants.go
  test/util/postgres.go
  test/util/util.go
Labels: cleanup

#25 added e2e for /chats endpoint
  go.mod
  internal/chat/repository/chat_repo_impl.go
  test/e2e/e2e_test.go
Labels: cleanup

#38 chore: get current user from context in service
  internal/chat/domain/chat_repo.go
  internal/chat/domain/chat_service.go
  internal/chat/http/chat_controller.go
  internal/chat/http/chat_service.go
  internal/chat/repository/chat_repo_impl.go
Labels: cleanup

#39 chore: user from context
  internal/chat/domain/chat_service.go
  internal/chat/http/chat_controller.go
  internal/common/domain/user.go
Labels: cleanup

#40 chore: token from context
  internal/common/domain/user.go
  internal/user/domain/user_service_impl.go
Labels: cleanup

#42 chore: propagate ctx on event handler
  internal/chat/domain/message_service_impl.go
  internal/chat/http/chat_controller.go
  internal/chat/websocket/connection.go
  internal/chat/websocket/create_message_handler.go
  internal/chat/websocket/event_handler.go
  internal/chat/websocket/set_current_chat_handler.go
  internal/chat/websocket/subscribe_chat_handler.go
  internal/chat/websocket/unset_current_room_handler.go
  internal/chat/websocket/unsubscribe_room_handler.go
  internal/chat/websocket/update_messages_status_handler.go
  internal/infrastructure/connector/connection.go
  internal/infrastructure/connector/connector.go
  internal/infrastructure/connector/event_handler.go
  internal/infrastructure/connector/websocket_connection.go
Labels: cleanup

#44 Revert "chore: propagate ctx on event handler"
  internal/chat/domain/message_service_impl.go
  internal/chat/http/chat_controller.go
  internal/chat/websocket/connection.go
  internal/chat/websocket/create_message_handler.go
  internal/chat/websocket/event_handler.go
  internal/chat/websocket/set_current_chat_handler.go
  internal/chat/websocket/subscribe_chat_handler.go
  internal/chat/websocket/unset_current_room_handler.go
  internal/chat/websocket/unsubscribe_room_handler.go
  internal/chat/websocket/update_messages_status_handler.go
  internal/infrastructure/connector/connection.go
  internal/infrastructure/connector/connector.go
  internal/infrastructure/connector/event_handler.go
  internal/infrastructure/connector/websocket_connection.go
Labels: cleanup

#37 Chat update
  internal/chat/domain/chat_service.go
  internal/chat/http/chat_controller.go
  internal/chat/http/chat_dto.go
  internal/chat/http/chat_mapper.go
  internal/chat/repository/chat_repo_impl.go
  test/e2e/e2e_test.go
  test/integration/api/chat_test.go
  test/util/chat.go
Labels: enhancement

#50 docs: readme
  .github/workflows/test.yaml
  README.md
Labels: documentation

#52 chore: remove ginkgo from hack tools
  Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/pinversion.go
Labels: cleanup

#53 chore: build and push docker image
  .github/workflows/build.yaml
Labels: cleanup

#54 chore: test only pull requests
  .github/workflows/test.yaml
Labels: cleanup
